apiVersion: v1
kind: ConfigMap
metadata:
  name: sreips-agent-config
  namespace: llamastack
data:
  LLAMA_STACK_URL: "https://lls-route-llamastack.apps.cluster-5tptd.5tptd.sandbox2399.opentlc.com/"
  MCP_ENDPOINT: "https://rh-kcs-mcp-servers.apps.cluster-5tptd.5tptd.sandbox2399.opentlc.com/sse"
  VECTOR_DB_ID: "sreips_vector_id"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sreips-agent
  namespace: llamastack
  labels:
    app: sreips-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sreips-agent
  template:
    metadata:
      labels:
        app: sreips-agent
    spec:
      containers:
      - name: sreips-agent
        image: quay.io/balki404/sreips-agent:0.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: sreips-agent
  namespace: llamastack
  labels:
    app: sreips-agent
spec:
  selector:
    app: sreips-agent
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sreips-agent
  namespace: llamastack
  labels:
    app: sreips-agent
spec:
  to:
    kind: Service
    name: sreips-agent
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

