apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: lsd-llama-milvus
spec:
  replicas: 1
  server:
    userConfig:                                                                                                                                  
      configMapName: llamastack-run-config                                                                                                 
      configMapNamespace: llamastack  
    containerSpec:
      resources:
        requests:
          cpu: "250m"
          memory: "500Mi"
        limits:
          cpu: "2"
          memory: "12Gi"
      env:
        - name: LLAMA_STACK_LOGGING
          value: "all=debug"
        - name: OPENAI_BASE_URL
          valueFrom:
            secretKeyRef:
              key: OPENAI_BASE_URL
              name: llama-stack-inference-model-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_API_KEY
              name: llama-stack-inference-model-secret      
        - name: INFERENCE_MODEL
          valueFrom:
            secretKeyRef:
              key: INFERENCE_MODEL
              name: llama-stack-inference-model-secret
        - name: VLLM_URL
          valueFrom:
            secretKeyRef:
              key: VLLM_URL
              name: llama-stack-inference-model-secret
        - name: VLLM_TLS_VERIFY
          valueFrom:
            secretKeyRef:
              key: VLLM_TLS_VERIFY
              name: llama-stack-inference-model-secret
        - name: VLLM_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: VLLM_API_TOKEN
              name: llama-stack-inference-model-secret
        # - name: MILVUS_DB_PATH
        #   value: ~/.llama/milvus.db
        # - name: FMS_ORCHESTRATOR_URL
        #   value: "http://localhost"
        - name: MILVUS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: milvus-secret
              key: MILVUS_ENDPOINT
        - name: MILVUS_TOKEN
          valueFrom:
            secretKeyRef:
              name: milvus-secret
              key: MILVUS_TOKEN
        - name: MILVUS_CONSISTENCY_LEVEL
          valueFrom:
            secretKeyRef:
              name: milvus-secret
              key: MILVUS_CONSISTENCY_LEVEL
        - name: POSTGRES_HOST
          value: postgres-llamastack.llamastack.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: database-name
              name: postgres-llamastack     
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: postgres-llamastack     
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: postgres-llamastack                 
      name: llama-stack
      port: 8321
    distribution:
      name: rh-dev

